pipeline
{
    agent any

    environment
    {
        RELEASE='20.04'
    }

    stages
    {
        stage('Build')
        {
            environment
            {
                LOG_LEVEL='INFO'
            }

            steps
            {
                echo "Building release for ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}..."
            }
        }

        stage('Test')
        {
            steps
            {
                echo "Testing release ${RELEASE}..."
                script
                {
                    if(Math.random() > 0.5)
                    {
                        throw new Execption()
                    }
                }
                writeFile file: 'test-results.txt', text: 'passed'
            }
        }
    }

    post
    {
        success
        {
            echo "Build succeeded"
            archiveArtifacts 'test-results.txt'
        }

        failure
        {
            echo "Build failed"
        }
    }
}